name: Spots notifier

on:
  push:
  schedule:
    - cron: "0 19 * * 2"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm install
      - name: Run script
        run: npm run scheduled
        env:
          PRIORIZE_WEEKENDS: ${{ secrets.PRIORIZE_WEEKENDS }}
          TELEGRAM_API_GROUP_ID: ${{ secrets.TELEGRAM_API_GROUP_ID }}
          TELEGRAM_API_TOKEN: ${{ secrets.TELEGRAM_API_TOKEN }}
